### ISSUE TITLE
Detailed training configurations?

### ISSUE THREAD

**Issue by jh-jeong** [jlindsey15/RetinalCode#1]
First of all, thanks for your incredible work in this ICLR!

I just want to reproduce your Retina+VVS, so could you share the detailed training scheme shortly? 
I tried to implement your work in PyTorch but seems there are some tough things inside, so that I couldn't see a clear Retina-like (or V1-like) RFs. Is there any detail omitted in your current paper?
Also, it seems that the code tries to maximize a single pixel of activation at the next layer (i.e. the objective) when you compute gradient for visualizing the RF for a layer. Am I understanding right? 

Thanks in advance!

**Comment by jlindsey15** [comment]
Hello!  Somewhat confusingly, this is not the code repository for our ICLR paper, but rather for a preliminary version of the project that led to that paper.  We will be releasing the code for the ICLR paper shortly, and when we do I will let you know and will be happy to answer any questions about it.

**Comment by jlindsey15** [comment]
Just wanted to let you know that the new code is up at https://github.com/ganguli-lab/RetinalResources.
